[project]
name = "transformergpt"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Saeedullah", email = "saeedullah.99992221@gamil.com" }
]
requires-python = ">=3.12"
dependencies = []

[project.scripts]
transformergpt = "transformergpt:main"

[build-system]
requires = ["uv_build>=0.12.16,<0.13.0"]
build-backend = "uv_build"
